INSERT INTO books (title, author_id, publication_date, isbn, description)
VALUES 
    ('To Kill a Mockingbird', (SELECT author_id FROM authors WHERE name = 'Harper Lee'), '1960-07-11', '9780061120084', 'To Kill a Mockingbird is a novel by Harper Lee published in 1960. It was immediately successful, winning the Pulitzer Prize, and has become a classic of modern American literature.'),
    ('1984', (SELECT author_id FROM authors WHERE name = 'George Orwell'), '1949-06-08', '9780451524935', '1984 is a dystopian novella by George Orwell published in 1949, which follows the life of Winston Smith, a low-ranking member of the Party, who is frustrated by the omnipresent eyes of the Party.'),
    ('The Great Gatsby', (SELECT author_id FROM authors WHERE name = 'F. Scott Fitzgerald'), '1925-04-10', '9780743273565', 'The Great Gatsby is a 1925 novel by F. Scott Fitzgerald set in the fictional town of West Egg on prosperous Long Island in the summer of 1922.'),
    ('Pride and Prejudice', (SELECT author_id FROM authors WHERE name = 'Jane Austen'), '1813-01-28', '9780141439518', 'Pride and Prejudice is an 1813 romantic novel of manners written by Jane Austen. The novel follows the character development of Elizabeth Bennet, the dynamic protagonist of the book, who learns about the repercussions of hasty judgments and eventually comes to appreciate the difference between superficial goodness and actual goodness.'),
    ('Harry Potter and the Philosopher''s Stone', (SELECT author_id FROM authors WHERE name = 'J.K. Rowling'), '1997-06-26', '9780590353427', 'Harry Potter and the Philosopher''s Stone is a fantasy novel written by British author J.K. Rowling. The first novel in the Harry Potter series and Rowling''s debut novel, it follows Harry Potter, a young wizard who discovers his magical heritage on his eleventh birthday, when he receives a letter of acceptance to Hogwarts School of Witchcraft and Wizardry.'),
    ('The Hobbit', (SELECT author_id FROM authors WHERE name = 'J. R. R. Tolkien'), '1937-09-21', '9780547928227', 'The Hobbit, or There and Back Again, is a children''s fantasy novel by English author J. R. R. Tolkien. It was published on 21 September 1937 to wide critical acclaim, being nominated for the Carnegie Medal and awarded a prize from the New York Herald Tribune for best juvenile fiction.'),
    ('To the Lighthouse', (SELECT author_id FROM authors WHERE name = 'Virginia Woolf'), '1927-05-05', '9780156907392', 'To the Lighthouse is a 1927 novel by Virginia Woolf. The novel centres on the Ramsays and their visits to the Isle of Skye in Scotland between 1910 and 1920 following and extended essay on woolf''s essay "modern fiction".'),
    ('Moby-Dick', (SELECT author_id FROM authors WHERE name = 'Herman Melville'), '1851-10-18', '9780142437247', 'Moby-Dick; or, The Whale is an 1851 novel by American writer Herman Melville. The book is the sailor Ishmael''s narrative of the obsessive quest of Ahab, captain of the whaling ship Pequod, for revenge on Moby Dick, the giant white sperm whale that on the ship''s previous voyage bit off Ahab''s leg at the knee.'),
    ('Jane Eyre', (SELECT author_id FROM authors WHERE name = 'Charlotte Brontë'), '1847-10-16', '9780142437209', 'Jane Eyre is a novel by English writer Charlotte Brontë, published under the pen name "Currer Bell" on 16 October 1847, by Smith, Elder & Co. of London.'),
    ('The Catcher in the Rye', (SELECT author_id FROM authors WHERE name = 'J. D. Salinger'), '1951-07-16', '9780316769488', 'The Catcher in the Rye is a novel by J. D. Salinger, partially published in serial form in 1945–1946 and as a novel in 1951. It was originally intended for adults, but is often read by adolescents for its themes of angst and alienation, and as a critique on superficiality in society.');
